const emojis={'-':' ','O':'🚪','X':'💣','I':'🎁','PLAYER':'💀','B':'🔥','GAME_OVER':'👎','WIN':'🏆','HEART':'🤍',};
const maps=[];
maps.push(`
  IXXXXXXXXX
  -XXXXXXXXX
  -XXXXXXXXX
  -XXXXXXXXX
  -XXXXXXXXX
  -XXXXXXXXX
  -XXXXXXXXX
  -XXXXXXXXX
  -XXXXXXXXX
  OXXXXXXXXX
  `);maps.push(`
  IXXXO-----
  -XXXXXXXX-
  -XXXXXXXX-
  -XXXXXXXX-
  -XXXXXXXX-
  -XXXXXXXX-
  -XXXXXXXX-
  -XXXXXXXX-
  -X---X----
  ---X---X--
`);maps.push(`
  O--XXXXXXX
  X--XXXXXXX
  XX----XXXX
  X--XX-XXXX
  X-XXX--XXX
  X-XXXX-XXX
  XX--XX--XX
  XX--XXX-XX
  XXXX---IXX
  XXXXXXXXXX
  `);maps.push(`
  I-----XXXX
  XXXXX-XXXX
  XX----XXXX
  XX-XXXXXXX
  XX-----XXX
  XXXXXX-XXX
  XX-----XXX
  XX-XXXXXXX
  XX-----OXX
  XXXXXXXXXX
  `);